- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/app
    backup: yes

- name: Enable site in Nginx
  file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

- name: Start Nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
