replicaCount: 2

image:
  tag: "latest"

frontend:
  replicaCount: 2
  image:
    repository: nginx
  service:
    port: 80

backend:
  replicaCount: 2
  image:
    repository: cowboymarlboro1884/simple-flask-app
  service:
    port: 5000
  livenessProbe:
    path: /health
  readinessProbe:
    path: /ready

ingress:
  enabled: true
  className: nginx
  host: ""
