apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    tier: frontend
data:
  default.conf: |
    upstream backend {
      server backend-service:{{ .Values.backend.service.port }};
    }

    server {
      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      location /api {
        proxy_pass http://backend;
      }

      location /health {
        proxy_pass http://backend/health;
      }
    }
