{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
